apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: safevixai
data:
  ENVIRONMENT: "production"
  CHATBOT_SERVICE_URL: "http://chatbot:8010/api/v1"
  REDIS_URL: "redis://redis:6379/0"
  CORS_ORIGINS: '["https://app.safevixai.com"]'
