apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safevixai-ingress
  namespace: safevixai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: app.safevixai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: safevixai-frontend-service
            port:
              number: 80
  - host: api.safevixai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: safevixai-backend-service
            port:
              number: 8000
  - host: chat.safevixai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: safevixai-chatbot-service
            port:
              number: 8010
