apiVersion: v1
kind: ServiceAccount
metadata:
  name: safevixai-backend
  namespace: safevixai
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/safevixai-backend-role
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: safevixai-chatbot
  namespace: safevixai
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/safevixai-chatbot-role
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: safevixai-frontend
  namespace: safevixai
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/safevixai-frontend-role
automountServiceAccountToken: false
