# SPDX-License-Identifier: MIT
# Copyright (c) 2026 SafeVixAI Team
blank_issues_enabled: true
contact_links:
  - name: SafeVixAI GitHub Discussions
    url: https://github.com/SafeVixAI/SafeVixAI/discussions
    about: Please ask and answer questions here
  - name: Security Issues
    url: https://github.com/SafeVixAI/SafeVixAI/security/policy
    about: Please report security vulnerabilities here
