# SPDX-License-Identifier: MIT
# Copyright (c) 2026 SafeVixAI Team
# deploy/logging-config.yaml
# Structured logging configuration for SafeVixAI
# All 3 services (backend, chatbot, frontend) emit JSON logs
---
version: 1
formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(timestamp)s %(level)s %(name)s %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'

handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout

loggers:
  safevixai:
    level: INFO
    handlers: [console]
    propagate: no
  safevixai.backend:
    level: INFO
    handlers: [console]
    propagate: no
  safevixai.chatbot:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn:
    level: WARN
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
