// SPDX-License-Identifier: MIT
// Copyright (c) 2026 SafeVixAI Team

// Auto-generated by scripts/generate-i18n-types.mjs. Do not edit manually.

interface authNS {
}

interface challanNS {
  "challan": {
    "calculator_active": string;
    "title": string;
    "total_liability": string;
    "loading": string;
    "detailed_report": string;
    "detailed_report_offline": string;
    "max_penalty": string;
    "act_sync": string;
    "violation_protocol": string;
    "vehicle_identification": string;
    "jurisdiction": string;
    "jurisdiction_tip": string;
    "history": string;
    "repeat_offender": string;
    "ai_guidance": string;
    "cached_result": string;
    "calculation_failed": string;
    "retry_calculation": string;
    "two_wheeler": string;
    "two_wheeler_sub": string;
    "car_lmv": string;
    "car_lmv_sub": string;
    "truck": string;
    "truck_sub": string;
    "bus_comm": string;
    "bus_comm_sub": string;
    "heavy": string;
    "light": string;
    "standard": string;
    "violation_183": string;
    "violation_179": string;
    "violation_185": string;
    "violation_181": string;
    "violation_194D": string;
    "danger_185": string;
    "first_occurrence": string;
    "repeat_offence": string;
    "ai_guidance_default": string;
    "rupees_symbol": string;
  };
}

interface chatNS {
  "chat": {
    "title": string;
    "subtitle": string;
    "online": string;
    "offline": string;
    "audio_enabled": string;
    "audio_disabled": string;
    "stop_reading": string;
    "auto_read_enable": string;
    "auto_read_disable": string;
    "suggested_inquiries": string;
    "show_suggested": string;
    "hide_suggested": string;
    "welcome_msg": string;
    "connection_interrupted": string;
    "copied": string;
    "clipboard_unavailable": string;
    "reading_aloud": string;
    "feedback_recorded": string;
    "retrying": string;
    "ask_placeholder": string;
    "starters": {
      "accident": string;
      "ambulance": string;
      "hit_and_run": string;
      "police_stop": string;
    };
    "select_language": string;
    "language_selection": string;
    "switch_online": string;
    "switch_offline": string;
    "copy": string;
    "read_aloud": string;
    "thumbs_up": string;
    "thumbs_down": string;
    "retry": string;
    "offline_ai_failed": string;
  };
}

interface commonNS {
  "nav": {
    "map": string;
    "assistant": string;
    "locator": string;
    "first_aid": string;
    "report_issue": string;
    "guide": string;
    "civic_intel": string;
    "challan": string;
    "emergency": string;
    "profile": string;
    "settings": string;
    "show_sidebar": string;
  };
  "emergency": {
    "dial_title": string;
    "emergency": string;
    "police": string;
    "ambulance": string;
    "highway": string;
    "system_sos": string;
    "system_online": string;
  };
  "bystander": {
    "bystander_mode": string;
    "title_witnessed": string;
    "title_accident": string;
    "description": string;
    "activate": string;
    "footer_note": string;
    "capturing_location": string;
    "gps_locking": string;
    "stay_calm": string;
    "all_steps_done": string;
    "steps_done_desc": string;
    "call_again": string;
    "show_on_maps": string;
    "protocol_active": string;
    "done": string;
    "gps_captured": string;
    "reported": string;
    "nearest_hospital": string;
    "follow_steps": string;
    "critical": string;
    "call_108": string;
    "call_112": string;
    "tts_gps_capture": string;
    "tts_gps_success": string;
    "tts_gps_fail": string;
    "report_description": string;
    "report_failed": string;
    "tts_calling_ambulance": string;
    "whatsapp_message": string;
    "steps": {
      "step_1": string;
      "step_2": string;
      "step_3": string;
      "step_4": string;
      "step_5": string;
      "step_6": string;
      "step_7": string;
      "step_8": string;
    };
  };
  "report": {
    "report_hazard": string;
    "report_live_road": string;
    "report_active": string;
    "approximate_gps": string;
    "title": string;
    "subtitle": string;
    "reporting_to": string;
    "helpline": string;
    "view": string;
    "location_lock": string;
    "refresh_location": string;
    "accuracy": string;
    "coordinates": string;
    "pending_device_fix": string;
    "approximate_location_warning": string;
    "evidence_capture": string;
    "optional_photo_uplink": string;
    "replace_photo": string;
    "attach_road_image": string;
    "optional_photo_hint": string;
    "report_form": string;
    "flag_hazard_title": string;
    "incident_category": string;
    "roads_label": string;
    "traffic_label": string;
    "streetlights_label": string;
    "hazard_type": string;
    "selected": string;
    "your_phone": string;
    "phone_placeholder": string;
    "severity": string;
    "notes_label": string;
    "notes_placeholder": string;
    "submit_button": string;
    "submitting": string;
    "reset": string;
    "report_uplinked": string;
    "report_uplinked_desc": string;
    "complaint_reference": string;
    "complaint_tagged": string;
    "duplicate_detected": string;
    "authority_desk": string;
    "tagged_road_asset": string;
    "sla_resolution_target": string;
    "guaranteed_response": string;
    "track_progress": string;
    "open_complaint_portal": string;
    "file_another_report": string;
    "live_authority_match": string;
    "waiting_authority_lookup": string;
    "road": string;
    "authority": string;
    "portal": string;
    "portal_not_listed": string;
    "escalation": string;
    "exec_engineer": string;
    "road_asset_intelligence": string;
    "metadata_pending": string;
    "road_type": string;
    "contractor": string;
    "budget_sanctioned": string;
    "next_maintenance": string;
    "not_published": string;
    "not_scheduled": string;
    "platform_title": string;
    "platform_desc": string;
    "nearby_help": string;
    "enable_location_authority": string;
    "unable_resolve_address": string;
    "road_ownership_unavailable": string;
    "infra_data_unavailable": string;
    "form_validation_error": string;
    "issue_types": {
      "pothole": string;
      "pothole_desc": string;
      "crack": string;
      "crack_desc": string;
      "waterlogging": string;
      "waterlogging_desc": string;
      "debris": string;
      "debris_desc": string;
      "footpath": string;
      "footpath_desc": string;
      "markings": string;
      "markings_desc": string;
      "signal_outage": string;
      "signal_outage_desc": string;
      "missing_sign": string;
      "missing_sign_desc": string;
      "zebra_crossing": string;
      "zebra_crossing_desc": string;
      "speed_bump": string;
      "speed_bump_desc": string;
      "encroachment": string;
      "encroachment_desc": string;
      "dark_street": string;
      "dark_street_desc": string;
      "bulb_out": string;
      "bulb_out_desc": string;
      "pole_damage": string;
      "pole_damage_desc": string;
      "electrical_hazard": string;
      "electrical_hazard_desc": string;
    };
    "severities": {
      "low": string;
      "low_desc": string;
      "guarded": string;
      "guarded_desc": string;
      "serious": string;
      "serious_desc": string;
      "critical": string;
      "critical_desc": string;
      "extreme": string;
      "extreme_desc": string;
    };
  };
  "locator": {
    "approximate_location": string;
    "routing": string;
    "resource_dispatch": string;
    "emergency_locator": string;
    "live_hud": string;
    "telemetry_active": string;
    "locator_subsystem": string;
    "emergency_resources": string;
    "found_facilities_one": string;
    "found_facilities_other": string;
    "approximate_location_warning": string;
    "approximate_location_warning_desktop": string;
    "gps_permission_error": string;
    "retry_gps": string;
    "finding_nearest": string;
    "no_hospitals_5km": string;
    "loading_desc": string;
    "other_filter_desc": string;
    "radius_widened_desc": string;
    "fallback_desc": string;
    "route_unavailable": string;
    "building_route": string;
    "calculating_clearest": string;
    "route_ready": string;
    "rerouting": string;
    "destination_selected": string;
    "provider": string;
    "route_options": string;
    "step_by_step": string;
    "open_external_nav": string;
    "call": string;
    "locate": string;
    "focus": string;
    "filters": {
      "All": string;
      "Hospital": string;
      "Police": string;
      "Fire": string;
      "Mechanic": string;
      "Towing": string;
    };
  };
  "auth": {
    "operator_email": string;
    "access_key": string;
    "enter_command_center": string;
    "authenticating": string;
    "all_fields_required": string;
    "sentinel_online": string;
    "jwt_secured": string;
  };
  "errors": {
    "invalid_credentials": string;
    "rate_limit_exceeded": string;
    "internal_server_error": string;
  };
  "validation": {
    "required_field": string;
    "invalid_email": string;
  };
}

interface dashboardNS {
  "dashboard": {
    "priority_vectors": string;
    "secure_region": string;
    "secure_region_sub": string;
    "caution_zone": string;
    "caution_zone_sub_one": string;
    "caution_zone_sub_other": string;
    "high_risk_area": string;
    "high_risk_area_one": string;
    "high_risk_area_sub_one": string;
    "high_risk_area_sub_other": string;
  };
  "map_layers": {
    "title": string;
    "satellite": string;
    "traffic": string;
    "safe_spaces": string;
    "hazard_heatmap": string;
    "emergency_services": string;
    "hazard_legend": string;
    "high_severity": string;
    "traffic_accident": string;
    "weather_flood": string;
    "relocate_sentinel": string;
    "tomtom_unavailable": string;
  };
}

interface errorsNS {
}

interface settingsNS {
  "settings": {
    "title": string;
    "subtitle": string;
    "signed_in": string;
    "profile_active": string;
    "active_user": string;
    "visual_interface": string;
    "appearance_mode": string;
    "light": string;
    "dark": string;
    "system": string;
    "safety_settings": string;
    "crash_detection": string;
    "crash_detection_sub": string;
    "speed_warnings": string;
    "speed_warnings_sub": string;
    "hazard_alerts": string;
    "hazard_alerts_sub": string;
    "sos_vibration": string;
    "sos_vibration_sub": string;
    "auditory_feedback": string;
    "auditory_feedback_sub": string;
    "navigation_app": string;
    "navigation_app_sub": string;
    "preferred_language": string;
    "preferred_language_sub": string;
    "location_privacy": string;
    "live_location": string;
    "live_location_sub": string;
    "auto_offline_bundle": string;
    "auto_offline_bundle_sub": string;
    "usage_analytics": string;
    "usage_analytics_sub": string;
    "privacy_note": string;
    "data_storage": string;
    "offline_cache": string;
    "offline_cache_sub": string;
    "export_profile": string;
    "export_profile_sub": string;
    "build_info_sub": string;
    "edit_profile": string;
    "edit_profile_sub": string;
    "emergency_protocols": string;
    "emergency_protocols_sub": string;
    "purge": string;
    "confirm_purge": string;
    "export": string;
    "signed_out": string;
    "analytics_enabled": string;
    "analytics_disabled": string;
    "purge_success": string;
    "export_success": string;
    "nav_set": string;
  };
  "profile": {
    "title": string;
    "subtitle": string;
    "save_flash": string;
    "profile_sync": string;
    "edit_profile": string;
    "cancel": string;
    "save": string;
    "avatar_url": string;
    "set_name": string;
    "active_vessel": string;
    "vehicle_number_placeholder": string;
    "vehicle_reg": string;
    "bio_signature": string;
    "select_blood": string;
    "emergency_broadcast": string;
    "phone_signature": string;
    "phone_placeholder": string;
    "mobile_number": string;
    "medical_record": string;
    "medical_placeholder": string;
    "biometric_anomalies": string;
    "emergency_contact": string;
    "sos_contact": string;
    "add_emergency": string;
    "safety_protocols": string;
    "offline_mode_label": string;
    "offline_mode_sub": string;
    "crash_detection_label": string;
    "crash_detection_sub": string;
    "push_hub_label": string;
    "push_hub_sub": string;
    "achievements": string;
    "sign_out": string;
    "confirm_purge": string;
    "purge_local": string;
    "security_layer": string;
    "badge_safety": string;
    "badge_responder": string;
    "badge_ai": string;
    "badge_active_user": string;
    "badge_trained": string;
    "badge_safevix": string;
    "session_purged_toast": string;
    "qr_card_title": string;
    "card_ready": string;
    "incomplete": string;
    "scan_in_emergency": string;
    "not_set": string;
    "none": string;
    "blood": string;
    "vehicle": string;
    "sos": string;
    "preview": string;
    "share_card": string;
    "copied_toast": string;
    "emergency_protocol": string;
    "close": string;
    "share": string;
    "unknown_operator": string;
    "incomplete_warning": string;
  };
}

interface validationNS {
}

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
      "auth": authNS;
      "challan": challanNS;
      "chat": chatNS;
      "common": commonNS;
      "dashboard": dashboardNS;
      "errors": errorsNS;
      "settings": settingsNS;
      "validation": validationNS;
    };
  }
}

export {};
