#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 SafeVixAI Team
"""
setup-monitoring.py — Generate monitoring config and setup instructions.

Produces .env.monitoring with recommended OTEL / Sentry / UptimeRobot config,
and prints step-by-step guides for each service.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path


def read_settings() -> dict:
    """Best-effort read of backend Settings class for env info."""
    settings = {}
    backend_env = Path("backend/.env")
    if backend_env.exists():
        for line in backend_env.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                settings[k.strip()] = v.strip()
    settings.setdefault("ENVIRONMENT", os.getenv("ENVIRONMENT", "development"))
    settings.setdefault("APP_NAME", "SafeVixAI Backend")
    return settings


MONITORING_TEMPLATE = """\
# ── SafeVixAI Monitoring Configuration ──
# Generated by scripts/setup-monitoring.py
# Environment: {environment}

# ── OpenTelemetry (Grafana Cloud / Axiom) ──
# Sign up at https://grafana.com (free 10k series / 14d retention)
OTEL_SERVICE_NAME={app_name}
OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.grafana.net:4318
# OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic base64(instanceId:token)"

# ── Sentry (free 5k events/month) ──
# Create project at https://sentry.io
# SENTRY_DSN=https://public@sentry.io/123

# ── Logging ──
LOG_LEVEL=INFO

# ── UptimeRobot (free 5 monitors) ──
# Create account at https://uptimerobot.com
UPTIMEROBOT_API_KEY=
UPTIMEROBOT_MONITOR_URL=https://your-backend.com/health
UPTIMEROBOT_INTERVAL_MINUTES=5
"""


def print_setup_instructions(settings: dict) -> None:
    env = settings.get("ENVIRONMENT", "development")
    app = settings.get("APP_NAME", "SafeVixAI")

    print("=" * 60)
    print(f"  SafeVixAI Monitoring Setup — {app} ({env})")
    print("=" * 60)

    print("""
1. UptimeRobot (Free Tier — 5 monitors, 5 min intervals)
   ├── Sign up: https://uptimerobot.com
   ├── Add new monitor:
   │   - Type: HTTP(s)
   │   - URL: https://<your-backend>/health
   │   - Interval: 5 minutes
   │   - Alert contacts: email
   └── Save the API key in .env.monitoring

2. Grafana Cloud (Free Tier — 10k prometheus series, 14d retention)
   ├── Sign up: https://grafana.com
   ├── Create a stack → Prometheus + Loki
   ├── Install OTEL collector or use OTEL exporter directly
   ├── Add OTEL env vars to backend/.env or deploy config
   └── Verify: metrics appear at /metrics endpoint

3. Sentry (Free Tier — 5k events/month)
   ├── Sign up: https://sentry.io
   ├── Create a Python (FastAPI) project
   ├── Copy the DSN into backend/.env as SENTRY_DSN
   └── Deploy — errors auto-capture via sentry_sdk.init in backend/main.py

4. Log Shipping (optional — free Axiom tier or Loki)
   ├── Axiom: https://axiom.co (500GB/month free)
   ├── or Loki via Grafana Cloud (included above)
   └── Ship structured logs from backend/ (JSON format)

5. Daily Backup Monitoring
   ├── Ensure pg_dump cron runs (see scripts/app/seed_pg_dump.py)
   ├── Check backup completeness daily
   └── Test restore quarterly
""")


def main():
    settings = read_settings()
    env_file = Path(".env.monitoring")
    env_file.write_text(MONITORING_TEMPLATE.format(
        environment=settings.get("ENVIRONMENT", "development"),
        app_name=settings.get("APP_NAME", "SafeVixAI Backend"),
    ))
    print(f"✔  Created {env_file}")
    print_setup_instructions(settings)


if __name__ == "__main__":
    main()
