"""add city to road_issues

Revision ID: 9c486bbc07a7
Revises: 10021
Create Date: 2026-08-02 13:33:03.981307

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c486bbc07a7'
down_revision = '10021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('road_issues', sa.Column('city', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_road_issues_city'), 'road_issues', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_road_issues_city'), table_name='road_issues')
    op.drop_column('road_issues', 'city')
    # ### end Alembic commands ###
